### ISSUE TITLE
failed when using aws default key_id aws/ssm 

### ISSUE THREAD

**Issue by jameszh** [BWITS/ssm_parameter_store#1]
looks like, with calling client.put_parameter, if you passed KeyId='aws/ssm', you will get InvalidKeyId
so in the case without key_id  option or key_id is set 'aws/ssm', KeyId can't be present when making put_parameter call.

**Comment by ozbillwang** [comment]
Could you please provide details include the error message first?

When you start to use SSM parameter store at the first time, kms key `aws/ssm` is created by aws as default.

If the key `aws/ssm` does not exist, you should provide the `key_id` in ansible task, remember to add `alias` in the key name.


```
- name: Create or update secure key/value pair with nominated kms key
  ssm_parameter_store:
    name: "Hello"
    description: "This is your first key"
    key_id: "alias/demo"
    string_type: "SecureString"
    value: "World"
```
